### ISSUE TITLE
Can I use this board for controlling Industrial Robot?

### ISSUE THREAD

**Issue by fdkssdks** [davisjp1822/arduino-rhubarb_mega_dio_protection#1]
Hello,

I was wondering if I can use this Board to control the PLC and late that PLC is communicating to Robot that way Board can send instructions to Robot via PLC and control the robot movements.

Does it sound like it is doable? Any suggestions you can give will be appreciated.

Thanks

**Comment by davisjp1822** [comment]
Hey!

With the current iteration of the board, I don't think that control would work well. The board only has inputs, it doesn't yet have any outputs that can be controlled.
